# Generated by Django 3.1 on 2021-06-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
        ('rebase_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(default='', editable=False, max_length=250)),
                ('valor_frase', models.IntegerField(default=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('user_frase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentencias', to='login_register.user')),
            ],
        ),
    ]
